# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk15

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту ruslandav@yandex.ru если сборка упала
notifications:
  email:
    recipients:
      -ruslandav@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="27a4e376-f045-4618-b2e8-9d7e4765d977"